### PR TITLE
Fix Modrinth and GitHub badges

### PR DESCRIPTION
**Pull request by triphora**

### CODE REVIEW

**Comment by Kira-NT** [comment]
Badges are complete mess right now, so thanks for a helping had :D

Also, as it turns out, there is such thing as `logo=curseforge` *(didn't know shields.io supports `simple-icons` now)*, so could you add this url parameter to CurseForge's badges in your PRs too, please?

**Comment by triphora** [comment]
Done

**Comment by triphora** [comment]
@Kir-Antipov Please make sure you merge this before the March 14th deadline.

**Comment by Kira-NT** [comment]
What will happen on the March 14th? The badges are already broken, so what's the deadline about? :D

**Comment by triphora** [comment]
Full removal of API v1. Currently the badges work for about 6 hours of the day and don't work for the other 16.

**Comment by Kira-NT** [comment]
Well, the badges don't really work the way they should already, so it doesn't matter that much.

I don't want to push commits to the main branch before I actually update the projects, and at the moment I have `mc-publish` to work on, and I don't think I'll be able to finish everything I need before the March 14th.

**Pull request closed without merging**
